Traceback (most recent call last):
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Allis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm
import openpyxl as xl
reklame_df = pd.read_excel("reklame_regneark.xlsx")

yearly_counts = reklame_df['√Ör'].value_counts().sort_index()
rolling_average = yearly_counts.rolling(window=5).mean()

fig, ax1 = plt.subplots(figsize=(10, 6))
ax1.bar(yearly_counts.index, yearly_counts, color='skyblue', label='Number of Ads')
ax2 = ax1.twinx()  
ax2.plot(rolling_average.index, rolling_average, color='darkred', label='5-Year Rolling Average')
ax2.set_ylabel('Rolling Average')  
ax1.set_xlabel('Year')
ax1.set_ylabel('Number of Ads')
ax1.set_title('Number of Ads per Year and 5-Year Rolling Average (1871-1910)')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
ax1.tick_params(axis='x', rotation=45)

plt.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 5[0m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcolors[39;00m [38;5;28;01mimport[39;00m LogNorm
[1;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01mopenpyxl[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxl[39;00m
[0;32m      6[0m reklame_df [38;5;241m=[39m pd[38;5;241m.[39mread_excel([38;5;124m"[39m[38;5;124mreklame_regneark.xlsx[39m[38;5;124m"[39m)
[0;32m      8[0m yearly_counts [38;5;241m=[39m reklame_df[[38;5;124m'[39m[38;5;124m√Ör[39m[38;5;124m'[39m][38;5;241m.[39mvalue_counts()[38;5;241m.[39msort_index()

[1;31mModuleNotFoundError[0m: No module named 'openpyxl'

